/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FORM;

import Helper.Auth;
import Helper.MsgBox;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author ADMIN
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnQLSach = new javax.swing.JButton();
        btnQLNguoiMuon = new javax.swing.JButton();
        btnQLPhieuMuon = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniLogin = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        mniDoiMK = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();
        JMenu2 = new javax.swing.JMenu();
        mniQLSach = new javax.swing.JMenuItem();
        mniQLPhieuMuon = new javax.swing.JMenuItem();
        mniQLNguoiMuon = new javax.swing.JMenuItem();
        mniQLNhanVien = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        nmiThongKe1 = new javax.swing.JMenuItem();
        mniThongKe2 = new javax.swing.JMenuItem();
        mniThongKe3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 204, 0));
        jToolBar1.setRollover(true);

        btnQLSach.setBackground(new java.awt.Color(255, 204, 0));
        btnQLSach.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQLSach.setForeground(new java.awt.Color(255, 255, 255));
        btnQLSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Book.png"))); // NOI18N
        btnQLSach.setText("Quản lý sách");
        btnQLSach.setFocusable(false);
        btnQLSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLSach.setMaximumSize(new java.awt.Dimension(121, 56));
        btnQLSach.setMinimumSize(new java.awt.Dimension(121, 56));
        btnQLSach.setPreferredSize(new java.awt.Dimension(93, 51));
        btnQLSach.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLSachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLSachMouseExited(evt);
            }
        });
        btnQLSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSachActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLSach);

        btnQLNguoiMuon.setBackground(new java.awt.Color(255, 204, 0));
        btnQLNguoiMuon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQLNguoiMuon.setForeground(new java.awt.Color(255, 255, 255));
        btnQLNguoiMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Clien list.png"))); // NOI18N
        btnQLNguoiMuon.setText("Quản lý độc giả");
        btnQLNguoiMuon.setFocusable(false);
        btnQLNguoiMuon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLNguoiMuon.setMaximumSize(new java.awt.Dimension(121, 56));
        btnQLNguoiMuon.setMinimumSize(new java.awt.Dimension(121, 56));
        btnQLNguoiMuon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLNguoiMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLNguoiMuonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLNguoiMuonMouseExited(evt);
            }
        });
        btnQLNguoiMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNguoiMuonActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLNguoiMuon);

        btnQLPhieuMuon.setBackground(new java.awt.Color(255, 204, 0));
        btnQLPhieuMuon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQLPhieuMuon.setForeground(new java.awt.Color(255, 255, 255));
        btnQLPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Notes.png"))); // NOI18N
        btnQLPhieuMuon.setText("Quản lý phiếu mượn");
        btnQLPhieuMuon.setFocusable(false);
        btnQLPhieuMuon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLPhieuMuon.setPreferredSize(new java.awt.Dimension(93, 50));
        btnQLPhieuMuon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLPhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLPhieuMuonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLPhieuMuonMouseExited(evt);
            }
        });
        btnQLPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLPhieuMuonActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLPhieuMuon);
        jToolBar1.add(jSeparator1);

        btnExit.setBackground(new java.awt.Color(255, 204, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/No.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setMaximumSize(new java.awt.Dimension(121, 56));
        btnExit.setMinimumSize(new java.awt.Dimension(121, 56));
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ THƯ VIỆN");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Library-building-300x300.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jMenu1.setText("Hệ thống");
        jMenu1.setMargin(new java.awt.Insets(5, 2, 5, 2));

        mniLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Key.png"))); // NOI18N
        mniLogin.setText("Đăng nhập");
        mniLogin.setMargin(new java.awt.Insets(5, 2, 5, 2));
        mniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoginActionPerformed(evt);
            }
        });
        jMenu1.add(mniLogin);

        mniLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Log out.png"))); // NOI18N
        mniLogout.setText("Đăng xuất");
        mniLogout.setMargin(new java.awt.Insets(5, 2, 5, 2));
        mniLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mniLogout);

        mniDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Refresh.png"))); // NOI18N
        mniDoiMK.setText("Đổi mật khẩu");
        mniDoiMK.setMargin(new java.awt.Insets(5, 2, 5, 2));
        mniDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMKActionPerformed(evt);
            }
        });
        jMenu1.add(mniDoiMK);
        jMenu1.add(jSeparator2);

        mniExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/No.png"))); // NOI18N
        mniExit.setText("Thoát");
        mniExit.setMargin(new java.awt.Insets(5, 2, 5, 2));
        jMenu1.add(mniExit);

        jMenuBar1.add(jMenu1);

        JMenu2.setText("Quản lý");
        JMenu2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        JMenu2.setMaximumSize(new java.awt.Dimension(63, 32767));
        JMenu2.setMinimumSize(new java.awt.Dimension(63, 20));

        mniQLSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Book.png"))); // NOI18N
        mniQLSach.setText("Quản lý sách");
        mniQLSach.setMargin(new java.awt.Insets(5, 2, 5, 2));
        mniQLSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLSachActionPerformed(evt);
            }
        });
        JMenu2.add(mniQLSach);

        mniQLPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Notes.png"))); // NOI18N
        mniQLPhieuMuon.setText("Quản lý phiếu mượn");
        mniQLPhieuMuon.setMargin(new java.awt.Insets(5, 2, 5, 2));
        mniQLPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLPhieuMuonActionPerformed(evt);
            }
        });
        JMenu2.add(mniQLPhieuMuon);

        mniQLNguoiMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Clien list.png"))); // NOI18N
        mniQLNguoiMuon.setText("Quản lý độc giả");
        mniQLNguoiMuon.setMargin(new java.awt.Insets(5, 2, 5, 2));
        mniQLNguoiMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLNguoiMuonActionPerformed(evt);
            }
        });
        JMenu2.add(mniQLNguoiMuon);

        mniQLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User.png"))); // NOI18N
        mniQLNhanVien.setText("Quản lý nhân viên");
        mniQLNhanVien.setMargin(new java.awt.Insets(5, 2, 5, 2));
        mniQLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLNhanVienActionPerformed(evt);
            }
        });
        JMenu2.add(mniQLNhanVien);

        jMenuBar1.add(JMenu2);

        jMenu4.setText("Thống kê");

        nmiThongKe1.setText("Số người đăng ký");
        nmiThongKe1.setMargin(new java.awt.Insets(4, 2, 4, 2));
        nmiThongKe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmiThongKe1ActionPerformed(evt);
            }
        });
        jMenu4.add(nmiThongKe1);

        mniThongKe2.setText("Số lượt mượn");
        mniThongKe2.setMargin(new java.awt.Insets(4, 2, 4, 2));
        mniThongKe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThongKe2ActionPerformed(evt);
            }
        });
        jMenu4.add(mniThongKe2);

        mniThongKe3.setText("Trạng thái phiếu mượn");
        mniThongKe3.setMargin(new java.awt.Insets(4, 2, 4, 2));
        mniThongKe3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThongKe3ActionPerformed(evt);
            }
        });
        jMenu4.add(mniThongKe3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLSachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLSachMouseEntered
        // TODO add your handling code here:
        setColor(btnQLSach);
    }//GEN-LAST:event_btnQLSachMouseEntered

    private void btnQLSachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLSachMouseExited
        resetColor(btnQLSach);
    }//GEN-LAST:event_btnQLSachMouseExited

    private void btnQLNguoiMuonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNguoiMuonMouseEntered
        // TODO add your handling code here:
        setColor(btnQLNguoiMuon);
    }//GEN-LAST:event_btnQLNguoiMuonMouseEntered

    private void btnQLNguoiMuonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNguoiMuonMouseExited
        // TODO add your handling code here:
        resetColor(btnQLNguoiMuon);
    }//GEN-LAST:event_btnQLNguoiMuonMouseExited

    private void btnQLPhieuMuonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLPhieuMuonMouseEntered
        // TODO add your handling code here:
        setColor(btnQLPhieuMuon);
    }//GEN-LAST:event_btnQLPhieuMuonMouseEntered

    private void btnQLPhieuMuonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLPhieuMuonMouseExited
        // TODO add your handling code here:
        resetColor(btnQLPhieuMuon);
    }//GEN-LAST:event_btnQLPhieuMuonMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        setColor(btnExit);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        resetColor(btnExit);
    }//GEN-LAST:event_btnExitMouseExited

    private void mniQLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLNhanVienActionPerformed
        // TODO add your handling code here:
        openQLNhanVien();
    }//GEN-LAST:event_mniQLNhanVienActionPerformed

    private void btnQLSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSachActionPerformed
        // TODO add your handling code here:
        openQLSach();
    }//GEN-LAST:event_btnQLSachActionPerformed

    private void btnQLNguoiMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNguoiMuonActionPerformed
        // TODO add your handling code here:
        openQLNguoiMuon();
    }//GEN-LAST:event_btnQLNguoiMuonActionPerformed

    private void btnQLPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLPhieuMuonActionPerformed
        // TODO add your handling code here:
        openQLPhieuMuon();
    }//GEN-LAST:event_btnQLPhieuMuonActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void mniDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMKActionPerformed
        // TODO add your handling code here:
        openDoiMatKhau();
    }//GEN-LAST:event_mniDoiMKActionPerformed

    private void nmiThongKe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmiThongKe1ActionPerformed
        // TODO add your handling code here:
        openThongKe(0);
    }//GEN-LAST:event_nmiThongKe1ActionPerformed

    private void mniThongKe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThongKe2ActionPerformed
        // TODO add your handling code here:
        openThongKe(1);
    }//GEN-LAST:event_mniThongKe2ActionPerformed

    private void mniThongKe3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThongKe3ActionPerformed
        // TODO add your handling code here:
        openThongKe(2);
    }//GEN-LAST:event_mniThongKe3ActionPerformed

    private void mniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoginActionPerformed
        // TODO add your handling code here:
        openLogin();
    }//GEN-LAST:event_mniLoginActionPerformed

    private void mniLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogoutActionPerformed
        // TODO add your handling code here:
        openLogout();
        
    }//GEN-LAST:event_mniLogoutActionPerformed

    private void mniQLNguoiMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLNguoiMuonActionPerformed
        // TODO add your handling code here:
        openQLNguoiMuon();
    }//GEN-LAST:event_mniQLNguoiMuonActionPerformed

    private void mniQLSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLSachActionPerformed
        // TODO add your handling code here:
        openQLSach();
    }//GEN-LAST:event_mniQLSachActionPerformed

    private void mniQLPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLPhieuMuonActionPerformed
        // TODO add your handling code here:
        openQLPhieuMuon();
    }//GEN-LAST:event_mniQLPhieuMuonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu2;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnQLNguoiMuon;
    private javax.swing.JButton btnQLPhieuMuon;
    private javax.swing.JButton btnQLSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mniDoiMK;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniLogin;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenuItem mniQLNguoiMuon;
    private javax.swing.JMenuItem mniQLNhanVien;
    private javax.swing.JMenuItem mniQLPhieuMuon;
    private javax.swing.JMenuItem mniQLSach;
    private javax.swing.JMenuItem mniThongKe2;
    private javax.swing.JMenuItem mniThongKe3;
    private javax.swing.JMenuItem nmiThongKe1;
    // End of variables declaration//GEN-END:variables
    void init() {
        this.setSize(1000, 600);
        this.setLocationRelativeTo(null);
        //this.setIconImage(XImage.getAppicon());

        new ChaoJDialog(this, true).setVisible(true);
        new Login2(this, true).setVisible(true);
    }

    void setColor(JButton btn) {
        btn.setBackground(Color.red);
    }

    void resetColor(JButton btn) {
        btn.setBackground(new Color(255, 204, 0));
    }

    void openQLSach() {
        if (Auth.isLogin()) {
            new QLSach().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openQLNguoiMuon() {
        if (Auth.isLogin()) {
            new QLNguoiMuon().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openQLPhieuMuon() {
        if (Auth.isLogin()) {
            new QLPhieuMuon().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openQLNhanVien() {
        if (Auth.isLogin()) {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền sử dụng chức năng này");
            } else {
                new QLNhanVien().setVisible(true);
            }
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void openDoiMatKhau() {
        if (Auth.isLogin()) {
            new DoiMatKhau().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    void exit() {
        if (MsgBox.confirm(this, "Bạn có muốn kết thúc làm việc?")){
        System.exit(0);
        }
    }

    void openThongKe(int index) {
        if (Auth.isLogin()) {
            if (Auth.isManager()) {
                ThongKeJDialog tk = new ThongKeJDialog();
                tk.selectTab(index);
                tk.setVisible(true);

            } else {
                MsgBox.alert(this, "Bạn không có quyền xem thống kê.");
            }
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    
    void openLogin(){
        if(Auth.isLogin()){
            MsgBox.alert(this, "Đã đăng nhập!");
        }else{
            new Login2(this, true).setVisible(true);
        }
    }
    void openLogout(){
        if(!Auth.isLogin()){
            MsgBox.alert(this, "Bạn chưa đăng nhập!");
        }else{
            new Login2(this, true).setVisible(true);
            Auth.clear();
            new Main().setVisible(false);
        }
    }
}
